name: SerienNummer
version: '${project.version}'
main: com.tom.seriennummer.Main
authors: [ Tom ]
depend: [Citizens]
description: Seriennummern
commands:
  seriennummer:
    description: Seriennummer hinzufügen/abrufen/entfernen